server:
  port: 8200
spring:
  application:
    name: consumer
eureka:
  instance:
    prefer-ip-address: true #\u6CE8\u518C\u670D\u52A1\u4F7F\u7528\u670D\u52A1ip\u5730\u5740
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/