server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false #\u4E0D\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230eureka\u4E0A
    fetch-registry: false #\u4E0D\u4ECEeureka\u4E0A\u83B7\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F
    service-url:
      defaultZone: http://localhost:8761/eureka/